[package]
name = "nfidb-transport"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
bytes.workspace = true
futures-util.workspace = true
local-ip-address.workspace = true
mdns-sd.workspace = true
mime_guess.workspace = true
nfidb-core.workspace = true
nfidb-protocol.workspace = true
parking_lot.workspace = true
rust-embed.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
webrtc.workspace = true
